Refactoring centos Vagrantfile

diff --git a/centos/7/Vagrantfile b/centos/7/Vagrantfile
--- a/centos/7/Vagrantfile
+++ b/centos/7/Vagrantfile
@@ -1,6 +1,12 @@
 # -*- mode: ruby -*-
 # vi: set ft=ruby :
 
+# Define variables, with default values, that are read from OS env vars
+host_name = ENV["VAGRANT_HOST_NAME"]  || "skel-centos-7"
+host_cpu  = ENV["VAGRANT_HOST_CPU"]   || "2"
+host_ram  = ENV["VAGRANT_HOST_NAME"]  || "2048"
+host_ip   = ENV["VAGRANT_HOST_IP"]    || "192.168.45.40"
+
 # All Vagrant configuration is done below. The "2" in Vagrant.configure
 # configures the configuration version (we support older styles for
 # backwards compatibility). Please don't change it unless you know what
@@ -13,7 +19,7 @@ Vagrant.configure("2") do |config|
   # Every Vagrant development environment requires a box. You can search for
   # boxes at https://vagrantcloud.com/search.
   config.vm.box = "centos/7"
-  config.vm.hostname = "centaur"
+  config.vm.hostname = host_name
   # Disable automatic box update checking. If you disable this, then
   # boxes will only be checked for updates when the user runs
   # `vagrant box outdated`. This is not recommended.
@@ -33,7 +39,7 @@ Vagrant.configure("2") do |config|
   # Create a private network, which allows host-only access to the machine
   # using a specific IP.
   # config.vm.network "private_network", ip: "192.168.33.10"
-  config.vm.network "private_network", ip: "192.168.10.110", :mac => "5C4500000010"
+  config.vm.network "private_network", ip: host_ip, :mac => "5C4500000010"
 
   # Create a public network, which generally matched to bridged network.
   # Bridged networks make the machine appear as another physical device on
@@ -54,10 +60,10 @@ Vagrant.configure("2") do |config|
   #   # Display the VirtualBox GUI when booting the machine
   #   vb.gui = true
   #
-   vb.name = "centaur"
+   vb.name = host_name
      # Customize the amount of memory on the VM:
-    vb.cpus = "2"
-    vb.memory = "1024"
+    vb.cpus = host_cpu
+    vb.memory = host_ram
    end
   #
   # View the documentation for the provider you are using for more
@@ -70,18 +76,22 @@ Vagrant.configure("2") do |config|
   #   apt-get update
   #   apt-get install -y apache2
   # SHELL
+#  config.vm.provision "shell", privileged: true, inline: <<-SHELL
+#        echo -e "~~~~~~ Confirming ansible installation... ~~~~~~"
+#        if ! yum list installed 2>&1 | grep ansible > /dev/null 2>&1;then
+#            echo -e "ansible not found; installing..."
+#            yum install -y ansible
+#        fi
+#        echo -e "ansible is installed"
+#        echo -e "~~~~~~ Running ansible playbook... ~~~~~~"
+#        if [[ ! -d /vagrant_data/fatline ]];then
+#            echo -e "!!! Could not locate ansible playbook folder !!!"
+#        else
+#            ansible-playbook -i /vagrant_data/fatline/hosts /vagrant_data/fatline/site.yml
+#        fi
+#   SHELL
+
   config.vm.provision "shell", privileged: true, inline: <<-SHELL
-        echo -e "~~~~~~ Confirming ansible installation... ~~~~~~"
-        if ! yum list installed 2>&1 | grep ansible > /dev/null 2>&1;then
-            echo -e "ansible not found; installing..."
-            yum install -y ansible
-        fi
-        echo -e "ansible is installed"
-        echo -e "~~~~~~ Running ansible playbook... ~~~~~~"
-        if [[ ! -d /vagrant_data/fatline ]];then
-            echo -e "!!! Could not locate ansible playbook folder !!!"
-        else
-            ansible-playbook -i /vagrant_data/fatline/hosts /vagrant_data/fatline/site.yml
-        fi
-   SHELL
+        echo -e "~~~~~~ Performing movein provisioning ~~~~~~"
+  SHELL
 end
